"use strict";
exports.__esModule = true;
var levelup = require('levelup');
var leveldown = require('leveldown');
exports.db = levelup(leveldown('./db'));
exports.db.close();
exports.tag_limit = 10000;
exports.key_currency = "nix";
exports.fee_by_size = 0.0001;
exports.log_limit = 10000000;
